### ISSUE TITLE
Packages missing in current linux-64 channels

### ISSUE THREAD

**Issue by sjanssen2** [mortonjt/workflow-manager-playground#1]
I copied "environment.yml" to my machine and executed "conda env create -f environment.yml"
The result is:
Using Anaconda Cloud api site https://api.anaconda.org
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
.Solving package specifications: .
Error:  Packages missing in current linux-64 channels: 
- appnope 0.1.0 py35_0
- aragorn 1.2.36 1
- bcftools 1.2 2
- bwa 0.7.12 1
- graphviz 2.38.0 3
- ipython 4.2.0 py35_1
- jpeg 8d 1
- prodigal 2.60 1
- python.app 1.2 py35_4
- samtools 1.2 2
- snakemake 3.5.5 py35_1

I also tried at barnacle producing the same type of error:
Error:  Packages missing in current linux-64 channels: 
- appnope 0.1.0 py35_0
- aragorn 1.2.36 1
- bcftools 1.2 2
- burrito 3b1dcc5 py35_0
- bwa 0.7.12 1
- diamond 0.7.12 1
- graphviz 2.38.0 3
- hmmer 3.1b2 0
- infernal 1.1.1 0
- ipython 4.2.0 py35_1
- jpeg 8d 1
- micronota 7050632 py35_0
- minced 0.2.0 1
- prodigal 2.60 1
- python.app 1.2 py35_4
- samtools 1.2 2
- scikit-bio 0.4.2dev py35_0
- snakemake 3.5.5 py35_1

**Comment by mortonjt** [comment]
Updated and fixed!!

**Comment by liston** [comment]
Anyone have the answer to this: NoPackagesFoundError: Package missing in current linux-64 channels: 
  - appnope 0.1.0 py36_0
This is after running: conda env create -n pandas-pydata-berlin-2017 -f environment.yml

**Comment by aernesto** [comment]
Hi, I have the same issue as the one @liston describes [above](https://github.com/mortonjt/workflow-manager-playground/issues/1#issuecomment-320053870).
Typing:  
```
$ conda env create -f environment.yml -n myenv
``` 
returned:  
```
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .........

NoPackagesFoundError: Package missing in current linux-64 channels: 
  - appnope 0.1.0 py36_0
```
I then tried:  
```
$ pip install appnope
Collecting appnope
  Downloading appnope-0.1.0-py2.py3-none-any.whl
Installing collected packages: appnope
Successfully installed appnope-0.1.0
```
And retried the `conda` command in vain:  
```
$ conda env create -f environment.yml -n myenv
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .........

NoPackagesFoundError: Package missing in current linux-64 channels: 
  - appnope 0.1.0 py36_0
```
